apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress
  namespace: cka-net-q3
spec:
  podSelector: 
    matchLabels:
      run: backend
  policyTypes:
  - Ingress
  ingress: []
